# Secret to store database credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: production
type: Opaque                        # opaque means generic secret
stringData:
  host: your-db-host                # add here value and give encoded value there 
  user: your-db-user
  password: your-db-password
