# Secret to store database credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: production
type: Opaque
stringData:
  host: your-db-host
  user: your-db-user
  password: your-db-password
